apiVersion: v1
kind: Service
metadata:
  name: qr-code-generator-service
spec:
  selector:
    app: qr-code-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer